export type Slot =
  | 'Amulet'
  | 'Ring'
  | 'Cape'
  | 'Head'
  | 'Chest'
  | 'Legs'
  | 'Boots'
  | 'Weapon'
  | 'Gloves'
  | 'Misc'
  | ''

export type ItemName =
  | 'Adventurer Boots'
  | 'Adventurer Cloak'
  | 'Ale'
  | 'Armet'
  | 'Arming Sword'
  | 'Badger Pendant'
  | 'Bandage'
  | 'Barbuta Helmet'
  | 'Bardic Pants'
  | 'Bardiche'
  | 'Battle Axe'
  | 'Buckler'
  | 'Campfire Kit'
  | 'Castillon Dagger'
  | 'Chapel De Fer'
  | 'Chaperon'
  | 'Clarity Potion'
  | 'Cloth Pants'
  | 'Cobalt Ingot'
  | 'Cobalt Ore'
  | 'Cobalt Powder'
  | 'Crossbow'
  | 'Crystal Ball'
  | 'Crystal Sword'
  | 'Dark Plate Armor'
  | 'Double Axe'
  | 'Doublet'
  | 'Drum'
  | 'Explosive Bottle'
  | 'Falchion'
  | 'Fangs of Death Necklace'
  | 'Feathered Hat'
  | 'Felling Axe'
  | 'Fine Cuirass'
  | 'Flanged Mace'
  | 'Flute'
  | 'Forest Hood'
  | 'Fox Pendant'
  | 'Francisca Axe'
  | 'Frock'
  | 'Frost Amulet'
  | 'Gjermundbu'
  | 'Gold Ingot'
  | 'Gold Ore'
  | 'Gold Powder'
  | 'Golden Key'
  | 'Grimsmile Ring'
  | 'Halberd'
  | 'Hand Crossbow'
  | 'Hatchet'
  | 'Healing Potion'
  | 'Heater Shield'
  | 'Heavy Boots'
  | 'Heavy Gauntlet'
  | 'Heavy Leather Leggings'
  | 'Horsemans Axe'
  | 'Hounskull'
  | 'Hunting Trap'
  | 'Invisibility Potion'
  | 'Kettle Hat'
  | 'Kris Dagger'
  | 'Laced Turnshoe'
  | 'Leather Bonnet'
  | 'Leather Cap'
  | 'Leather Chausses'
  | 'Leather Gloves'
  | 'Leather Leggings'
  | 'Lightfoot Boots'
  | 'Lockpick'
  | 'Longbow'
  | 'Longsword'
  | 'Loose Trousers'
  | 'Lute'
  | 'Lyre'
  | 'Marauder Outfit'
  | 'Morning Star'
  | 'Mystic Vestments'
  | 'Necklace of Peace'
  | 'Northern Full Tunic'
  | 'Occultist Boots'
  | 'Occultist Hood'
  | 'Occultist Robe'
  | 'Occultist Tunic'
  | 'Oil Lantern'
  | 'Old Rusty Key'
  | 'Old Shoes'
  | 'Oracle Robe'
  | 'Ox Pendant'
  | 'Padded Leggings'
  | 'Padded Tunic'
  | 'Pavise'
  | 'Phoenix Choker'
  | 'Pickaxe'
  | 'Plate Boots'
  | 'Plate Pants'
  | 'Potion of Luck'
  | 'Potion of Protection'
  | 'Quarterstaff'
  | 'Radiant Cloak'
  | 'Ranger Hood'
  | 'Rapier'
  | 'Rat Pendant'
  | 'Rawhide Gloves'
  | 'Recurve Bow'
  | 'Regal Gambeson'
  | 'Reinforced Gloves'
  | 'Ring of Courage'
  | 'Ring of Quickness'
  | 'Ring of Resolve'
  | 'Ring of Survival'
  | 'Riveted Gloves'
  | 'Rogue Cowl'
  | 'Rondel Dagger'
  | 'Round Shield'
  | 'Rubysilver Ingot'
  | 'Rubysilver Ore'
  | 'Rubysilver Powder'
  | 'Rugged Boots'
  | 'Shadow Hood'
  | 'Shadow Mask'
  | 'Short Sword'
  | 'Skull Key'
  | 'Spear'
  | 'Spellbook'
  | 'Splendid Cloak'
  | 'Stiletto Dagger'
  | 'Straw Hat'
  | 'Surgical Kit'
  | 'Survival Bow'
  | 'Tattered Cloak'
  | 'Templar Armor'
  | 'Test'
  | 'Throwing Knife'
  | 'Torq of Soul'
  | 'Trolls Blood'
  | 'Troubadour Outfit'
  | 'Viking Helmet'
  | 'Viking Sword'
  | 'Visored Barbuta Helmet'
  | 'Wanderer Attire'
  | 'War Maul'
  | 'Warden Outfit'
  | 'Wind Locket'
  | 'Windlass Crossbow'
  | 'Wizard Hat'
  | 'Wizard Shoes'
  | 'Wizard Staff'
  | 'Zweihander'
  | ''
