name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: pull request
      run: |
           cd /
           cd /opt/darkertrade/
           git pull
    - name: update FE
      run: |
          cd /
          cd /opt/darkertrade/
          cd /frontend/
          pnpm i
    - name: start FE 
      run: pm2 start "pnpm run build" --name FE    
    - name: update BE
      run: |
          cd /
          cd /opt/darkertrade/
          cd /backend/
          pnpm i 
    - name: start BE 
      run: pm2 start "nest start" --name BE
    
