name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: pull request
      uses: actions/checkout@v2
    - name: pull request
      run: git pull
    - name: update FE
      run: |
          cd /frontend/
          pnpm i 
      working-directory: /opt/darkertrade/
    - name: start FE 
      run: pm2 start "pnpm run build" --name FE    
    - name: update BE
      run: |
          cd ../backend/
          pnpm i 
      working-directory: /opt/darkertrade/
    - name: start BE 
      run: pm2 start "nest start" --name BE
    
