name: CI
on:
  push:
    branches:
      - 'main'
      - '!development'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: pull request
      run: |
           cd /
           cd /opt/darkertrade/
           git pull
    - name: update FE
      run: |
          cd /
          cd /opt/darkertrade/
          cd frontend
          pnpm i  
    - name: update BE
      run: |
          cd /
          cd /opt/darkertrade/
          cd backend
          pnpm i 
    - name: restart PM2
      run: pm2 restart /opt/darkertrade/ecosystem.config.js
    
